server:
  port: 8080
  address: 127.0.0.1
spring:
  application:
    name: demo # 项目名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource      # 数据库连接池 一般使用默认
    url: jdbc:mysql://localhost:3306/todo_list?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true # url
    username: root      # 数据库账号
    password: root      # 数据库密码
    druid:
      initialSize: 20
      minIdle: 20
      maxActive: 100
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
  data:
    redis: # redis配置
      host: localhost    # Redis服务器地址
      database: 0
      port: 6379    # Redis服务器连接端口
      password: root    # Redis服务器连接密码（默认为空）
      timeout: 10s    # 连接超时时间
      lettuce:
        pool:
          max-active: 8   # 连接池最大连接数
          max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10    # 连接池中的最大空闲连接
          min-idle: 0   # 连接池中的最小空闲连接
          timeout: 10000 # 连接超时时间
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8
mybatis-plus:
  global-config:
    #    identifierGenerator: 0     # 主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
    banner: false     # 关闭MP3.0自带的banner
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    mapUnderscoreToCamelCase: true # 数据库下划线自动转驼峰
    callSettersOnNulls: true      # 返回类型为Map,显示null对应的字段
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl     # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  mapperLocations: classpath*:/mappers/*Mapper.xml

cors:
  allowed: true

#jwt配置
jwt:
  tokenHeader: Authorization
  secret: ZJXoulwqnRtULX4VyQmblElx5qPDhhdb   # 加密的密钥
  expiration: 604800                        # JWT的超期限时间(60*60*24*7)
  tokenStart: Bearer

# AES 加密
aes:
  secret: 96H9WltRjOLw9wCl

springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"

    # JWT负载中拿到开头